const ID_PLACEHOLDER  = '{id}'

const URL_GET_IDEAS_LIST = '/art_ideas'
const URL_GET_IDEAS_DETAILS = '/art_ideas/'
const URL_GET_REFERENCE_MATERIAL = "/reference_materials"

const URL_CREATE_ART_IDEA = URL_GET_IDEAS_LIST;
const URL_CREATE_REFERENCE_MATERIAL = URL_GET_REFERENCE_MATERIAL;
const URL_CREATE_ART_TITLE = URL_CREATE_ART_IDEA + '/' + ID_PLACEHOLDER +'/titles';
const URL_UPDATE_ART_TITLE = URL_CREATE_ART_TITLE + '/' + ID_PLACEHOLDER;
const URL_DELETE_ART_TITLE = URL_UPDATE_ART_TITLE;
const URL_SET_TITLE_PRIMARY = URL_CREATE_ART_TITLE + '/primary';


const URL_CREATE_ART_QUESTION = URL_CREATE_ART_IDEA + '/' + ID_PLACEHOLDER +'/questions';
const URL_UPDATE_ART_QUESTION = URL_CREATE_ART_QUESTION + '/' + ID_PLACEHOLDER;


// types of images, based on definitions on backend
// since these likely won't change
// they are for now hardcoded here
const IDEA_TYPE_IMAGE = "image"
const IDEA_TYPE_IMAGE_TEXT = "image_with_caption"
const IDEA_TYPE_TEXT_ONLY = "caption_only"

// other enums, currently are hardcoded
const TITLE_TYPE_PRIMARY  = "primary"
const TITLE_TYPE_NOMINAL = "nominal"
const TITLE_TYPE_ALTERNATIVE = "alternative"

const REFERENCE_TYPE_IMAGE = "image";
const REFERENCE_TYPE_TUTORIAL_VIDEO = "tutorial_video";
const REFERENCE_TYPE_TUTORIAL_ARTICLE = "tutorial_article";
const REFERENCE_TYPE_PROMPT = "prompt";

const STORAGE_TYPE_LOCAL_DISK = "local_disk"
const STORAGE_TYPE_URL_LINK = "url_link"

export {
    // id
    ID_PLACEHOLDER,
    // urls
    URL_GET_IDEAS_LIST,   
    URL_GET_IDEAS_DETAILS,
    URL_GET_REFERENCE_MATERIAL,
    URL_CREATE_ART_IDEA,
    URL_CREATE_REFERENCE_MATERIAL,
    URL_CREATE_ART_QUESTION,
    URL_DELETE_ART_TITLE,
    URL_UPDATE_ART_QUESTION,
    URL_CREATE_ART_TITLE,
    URL_UPDATE_ART_TITLE,
    URL_SET_TITLE_PRIMARY,
    // types, enums on backend
    IDEA_TYPE_IMAGE,
    IDEA_TYPE_IMAGE_TEXT,
    IDEA_TYPE_TEXT_ONLY,
    REFERENCE_TYPE_IMAGE, 
    REFERENCE_TYPE_TUTORIAL_VIDEO, 
    REFERENCE_TYPE_TUTORIAL_ARTICLE,
    REFERENCE_TYPE_PROMPT, 
    STORAGE_TYPE_LOCAL_DISK, 
    STORAGE_TYPE_URL_LINK,
    TITLE_TYPE_PRIMARY,
    TITLE_TYPE_NOMINAL,
    TITLE_TYPE_ALTERNATIVE,
}